### ISSUE TITLE
Tube connectors missing in BOM

### ISSUE THREAD

**Issue by berezovskyi** [radhoo/uradmonitor_kit1#1]
Hi, I looked at the https://github.com/radhoo/uradmonitor_kit1/blob/master/pcb-1.1/res/uRADMonitor_KIT1.1_bom.txt#L7 but found no connectors (slots) in BOM for the SBM-20 tube.

Do you have any hints on how to find them?

**Comment by radhoo** [comment]
Hello, please use fuse holders, 6mm diameter as connectors.

**Comment by berezovskyi** [comment]
Brilliant, @radhoo! I think the best way for others to find them would be to search for _6.3mm (1/4") fuse clip_

**Comment by berezovskyi** [comment]
Littelfuse 01020071Z seems to be a good generic part

**Comment by radhoo** [comment]
Yes, and there are very affordable ones on Ebay as well.  I got a bag of
100pcs for just a few dollars.
