### ISSUE TITLE
Inductor specification

### ISSUE THREAD

**Issue by jetty840** [radhoo/uradmonitor_kit1#11]
Purchased a 2.2mH inductor (34Ohm) didn't work well.  Only was able to reach 380V with the inverter, and inverter was unstable and then entered discontinuous mode and voltage started dropping due to the light load.  If left to auto tune, tuned to 90% duty cycle (even if picking 370V as the target).  Also tried varying frequency, same result.

Hand wound indicator (2.3mH - 6Ohm) (i.e. same inductance, less resistance), resulted in the same.

So hand wound a 4.4mH 10.28Ohm (2.7 Q 5.7uF parasitic, 450 turns) around a ferrite core (450 turns).

Now by reducing the frequency to 9KHz, I get a stable region at around 65% duty cycle and can lock on to 400V without any issues.  The increased inductance prevents the boost circuit from entering discontinuous mode.

I suspect the inductance value in the BOM is at the lower limit of marginal, and either should be increased or the inductor used fully specified.

**Comment by radhoo** [comment]
The inductor is the 2.2mH 25Ohm Ring Inductance 0.5W size 0410. The duty cycle has been improved in v1.2.106 see the new component values.
