### ISSUE TITLE
Regulator voltage

### ISSUE THREAD

**Issue by jetty840** [radhoo/uradmonitor_kit1#12]
The regulator voltage of 3.0V is too low.  The minimum for the ENC28J60 is 3.1V according to the datasheet, and I've noticed erratic behavior in the 2.9V - 3.0V range which is around the level of the low battery indicator.  For example, at 2.95V my ENC28J60 won't startup 50% of the time.

I suggest 3.3V for the regulator if using ethernet.

**Comment by radhoo** [comment]
v1.2.105 and newer uses the AMS1117 3.3V regulator.
