### ISSUE TITLE
aux_detectorFactor for GEIGER_TUBE_SBM20 - CPM to µSv/h conversion

### ISSUE THREAD

**Issue by Trickx** [radhoo/uradmonitor_kit1#16]
Hi,

I'm trying to calibrate my Geiger counter based on a SBM20 tube.
Within your code, I found the conversion factor of 0.006315 from CPM (counts per minute) towards µSievert/h. (Invers conversion factor: 158,35.)
There are various conversion factors being reported in the web. This one is one of the famous ones.

Did you somehow calibrate your device? How did you derive this factor?

Actually I gave up to calculate the conversion factor.
I think I read all of the discussions about this topic in the English or German intrnet,
so I tried to find a reference for my location and calibrate it that way.

I'm located in Lehrte, Germany and see about 18 ticks in average with my SBM20 tube.
The German Bundesamt für Strahlenschutz (Federal Office for Radiation Protection - BfS) operates some monitoring stations acros Germany. Luckily there is one located in Lehrte, see
https://odlinfo.bfs.de/DE/aktuelles/messstelle/032530101.html
The average of this station seems to be around ~0,075 Sv/h.
This leads to a conversion factor of ~ 0,0041666 (inverse= 240).
Unfortuantely, I could not find more details about the station itself.

On https://www.uradmonitor.com/ I found a station located in Uelzen:
https://www.uradmonitor.com/?open=13000206
The station's average is 0.10µSv/h.

The BfS reports for Uelzen 0,066µSv/h, see
https://odlinfo.bfs.de/DE/aktuelles/messstelle/033600252.html

So there is a mismatch of the reported values.
Interestingly, it is the same deviation as I would see with the conversion factor of this project.

If the uradmonitor from Uelzen would use my conversion factor instead of the one from this code,
the calculated radiation dosis for Uelzen becomes: 
0.10µSv/h * 158,35 / 240 = 0,0657µSv/h, which is quit close to the value reported by BfS.

Of course this is just an indication but I think this demonstrates a common error.
I did not spend the time to check more stations.

I just would like to get more details about the calibration done for this project and why this way was choosen.

Thank you in advance,
Trickx

**Comment by radhoo** [comment]
Sorry for the slow reply. The conversion factor has been tested for quite some time now, given the size and spread of this project. But you can see how it was tested in its early phase in this article I posted: https://www.pocketmagic.net/global-radiation-monitoring-network/#140113
For easier communication, please drop me an email.

Thanks!
