### ISSUE TITLE
Routing incomplete?

### ISSUE THREAD

**Issue by madmax76** [radhoo/uradmonitor_kit1#2]
Hi,

Opening the 1.1 board in Eagle shows me that some traces have not been routed. Is that correct? After manually checking, it seems all is oke, but I want to etch the board, so I need to make sure that no errors are in the board. Seems like the Nokia LCD display has some magic via's on it, that I am unaware of.

Best regards,
Max

**Comment by radhoo** [comment]
That is correct, the Nokia display continues those routes. No mistakes here, feel free to etch.
