### ISSUE TITLE
tube type is hardcoded?

### ISSUE THREAD

**Issue by twanek** [radhoo/uradmonitor_kit1#4]
**issue:**
the tube type it seems to be hardcoded in uRADMonitor.cpp @ lines 351, 359:

`#ifdef USE_BME280_SENSOR
                    sprintf_P(ethParams, PSTR(ID_TIME_SECONDS"/%lu/"ID_VERSION_HW"/%u/"ID_VERSION_SW"/%u/"
                            ID_SBM20_CPM"/%lu/"ID_INVERTERVOLTAGE_VOLTS"/%u/"ID_INVERTERDUTY_PM"/%u/"
                            ID_TEMPERATURE_CELSIUS"/%.2f/"ID_PRESSURE_PASCALS"/%lu/"ID_HUMIDITY_RH"/%u"),
                            time.getTotalSec(), (uint8_t)VER_HW, (uint8_t)VER_SW,
                            data.getGeigerCPM(),data.getInverterVoltage(), data.getInverterDuty(),
                            data.getTemperature(), data.getPressure(), data.getHumidity()
                        );
# else

```
                sprintf_P(ethParams, PSTR(ID_TIME_SECONDS"/%lu/"ID_VERSION_HW"/%u/"ID_VERSION_SW"/%u/"
                                            ID_SBM20_CPM"/%lu/"ID_INVERTERVOLTAGE_VOLTS"/%u/"ID_INVERTERDUTY_PM"/%u"),
                        time.getTotalSec(), (uint8_t)VER_HW, (uint8_t)VER_SW,
                        data.getGeigerCPM(),data.getInverterVoltage(), data.getInverterDuty()
                    );`
```

**result:**
in the graph window it always shows "sbm20" type, regardless what is set by the user.

![tube2](https://cloud.githubusercontent.com/assets/17336510/19420276/944cf5d0-93f0-11e6-88c1-a3ea86608c8f.png)

**Comment by radhoo** [comment]
tube id added to the list of parameters, in SW v123:

```
sprintf_P(ethParams, PSTR(ID_TIME_SECONDS"/%lu/"ID_VERSION_HW"/%u/"ID_VERSION_SW"/%u/"
							ID_GEIGER_CPM"/%lu/"ID_INVERTERVOLTAGE_VOLTS"/%u/"ID_INVERTERDUTY_PM"/%u/"
							ID_TEMPERATURE_CELSIUS"/%.2f/"ID_PRESSURE_PASCALS"/%lu/"ID_HUMIDITY_RH"/%.2f/"ID_TUBE"/%u"),
							time.getTotalSec(), (uint8_t)VER_HW, (uint8_t)VER_SW,
							data.getGeigerCPM(),data.getInverterVoltage(), data.getInverterDuty(),
							data.getTemperature(), data.getPressure(), data.getHumidity(), GEIGER_TUBE
						);
```
