### ISSUE TITLE
in firmware v122, temperature value has only 1 degree resolution

### ISSUE THREAD

**Issue by twanek** [radhoo/uradmonitor_kit1#5]
i'm not sure if it is from wrong compilation settings, or a bug in the code, but the temperature value is displayed only as int on my device display / local site / server.
so, it has only one degree resolution...  :(

**Comment by rateyo** [comment]
Replace the following line in bme280.cpp as shown in order to evaluate the temperatur as floating point. 

```
void BME280::readSensors(float *temperature, uint32_t *pressure, uint8_t *humidity) {
	
	//*temperature =  (((t_fine * 5 + 128) >> 8) / 100) ;
	*temperature =  ((float)((t_fine * 5 + 128) >> 8) / 100) ;

```

**Comment by radhoo** [comment]
fixed in v123
