### ISSUE TITLE
Silkscreen PCB 1.2.105 - Transistors on HV part

### ISSUE THREAD

**Issue by MalteP** [radhoo/uradmonitor_kit1#7]
On the PCB silkscreen the text for T1 is marked with the wrong type "2N2907" and T6 is marked with "MPSA42" which should be swapped.

**Comment by radhoo** [comment]
Yes, you are right. I will fix it soon. Thanks! (please see my other email, I just sent you).

**Comment by andrew-xdn** [comment]
Hello! Found the same issue on the image files (uradmonitor_kit1/pcb/1.2.105/circuit/kit1_105_pcb.png, http://www.uradmonitor.com/wordpress/wp-content/uploads/2016/10/pcb_opensource_kit_105_pcb.jpg). It's a little confusing if you use one of the images to mount components.

**Comment by jetty840** [comment]
Only caught that one by accident when I was looking for the part in Eagle

**Comment by radhoo** [comment]
fixed in 1.2.106
