### ISSUE TITLE
Tube length

### ISSUE THREAD

**Issue by jetty840** [radhoo/uradmonitor_kit1#9]
The SBM-20 I had (marked SBM-20) was too large to fit the PCB and I needed to respin it.

According to the lengths on:  https://www.gstube.com/data/2398/, I have a SBM-20, and KIT1 is for a SBM-20U

I received the tube with my MightyOhm kit about 2 years ago and it fitted that board, so suspect there maybe multiple sizes of double end capped tube labelled SBM-20 as the SBM-20U has one end cap missing

Recommend adding a 2nd position for the clip on the board for the larger length tube.

**Comment by radhoo** [comment]
The design is for SBM20. The tube fits fine, please see the pictures. 
![kit1](https://www.uradmonitor.com/wordpress/wp-content/uploads/2017/08/kit1.2_and_variants.jpg)
